---
- name: Deploy Your Node.js Application
  hosts: nodejs_servers
  become: yes

  tasks:
    - name: Copy application files excluding node_modules
      synchronize:
        src: "/var/lib/jenkins/workspace/frontjenkins/build"
        dest: "/home/thyler/frontjenkins"
        delete: yes
        recursive: yes
